model:
  name: "Encoder"
  vocab_size: null  
  embedding_dim: 128
  hidden_size: 256
  num_layers: 5
  dropout: 0.3
  num_tags: null  

data:
  train_path: "dataset/PhoNER/train_word.json"
  dev_path: "dataset/PhoNER/dev_word.json"
  test_path: "dataset/PhoNER/test_word.json"
  max_length: 128
  batch_size: 32
  num_workers: 0

training:
  num_epochs: 20
  learning_rate: 0.001
  device: "cuda" 

paths:
  log_dir: "logs"
  model_save_dir: "models"
  model_name: "encoder_best_model.pt"